blogs/urls.py
from blogs.apps import BlogConfig
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    # path('', HomePage.as_view(), name='home'),
    # path('blogs/', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='blog_info'),
    path('create', BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    ContactsView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, MailingAttemptView, \
    mailing_status, HomePage

app_name = MailingsConfig.name

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('mailings/', MailingListView.as_view(), name='mailings_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_info'),
    path('mailings/create', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('attempts/', MailingAttemptView.as_view(), name='attempts_info'),
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_info'),
    path('clients/create', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', MessageListView.as_view(), name='messages_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_info'),
    path('messages/create', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('contacts/', cache_page(60)(ContactsView.as_view()), name='contacts'),
    path("activation/<int:pk>/", mailing_status, name="mailing_status"),

]

blogs/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField

from blogs.models import Blog


class FormMixin:
    """Класс для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogForm(FormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ('count_views', 'slug', 'created_at', 'owner_blog',)


class BlogModeratorForm(FormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ('count_views', 'slug', 'created_at', 'owner_blog',)

mailings/forms.py
from django.forms import ModelForm, BooleanField

from mailings.models import Client, Message, Mailing, MailingAttempt


class FormMixin:
    """Класс для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(FormMixin, ModelForm):
    """Класс для создание форм для модели Клиенты"""

    class Meta:
        model = Client
        exclude = ('owner_client',)


class ClientModeratorForm(FormMixin, ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MessageForm(FormMixin, ModelForm):
    """Класс для создание форм для модели Сообщения"""

    class Meta:
        model = Message
        exclude = ('owner_message',)


class MessageModeratorForm(FormMixin, ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class MailingForm(FormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner_mailing',)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields['message'].queryset = Message.objects.filter(owner_message=user)
        self.fields['clients'].queryset = Client.objects.filter(owner_client=user)


class MailingModeratorForm(FormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_active',)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(MailingModeratorForm, self).__init__(*args, **kwargs)


class MailingAttemptForm(FormMixin, ModelForm):
    class Meta:
        model = MailingAttempt
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    #     user = kwargs.pop('user')
    #     super(MailingAttemptForm, self).__init__(*args, **kwargs)
    #     self.fields['mailing'].queryset = Mailing.objects.filter(owner_mailing=user)
    #
    #     self.fields['clients'].queryset = Client.objects.filter(owner_client=user)

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blogs.forms import BlogForm, BlogModeratorForm
from blogs.models import Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mailings:home')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogs.Edit_entries'):
            return BlogModeratorForm
        else:
            raise PermissionDenied

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogModeratorForm

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogs.Edit_entries'):
            return BlogModeratorForm
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse('blogs:blog_info', args=[self.kwargs.get('slug')])


class BlogDeleteView(DeleteView):
    model = Blog

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogs.Edit_entries'):
            return BlogModeratorForm
        else:
            raise PermissionDenied

mailings/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from blogs.models import Blog
from mailings.forms import MailingForm, ClientForm, MessageForm, MailingModeratorForm, MailingAttemptForm
from mailings.models import Client, Message, Mailing, MailingAttempt


class MailingListView(LoginRequiredMixin, ListView):
    """Контроллер отображения страницы с расылками"""
    model = Mailing

    # success_url = reverse_lazy("mailing:home")

    def get_queryset(self):
        user = self.request.user
        if user.has_perm('mailings.View_any_mailing_lists'):
            return super().get_queryset()
        return super().get_queryset().filter(owner_mailing=user)


class MailingDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Контроллер для просмотра рассылки"""
    model = Mailing

    def test_func(self):
        user = self.request.user
        mailing = self.get_object()
        if user == mailing.owner_mailing:
            return True
        elif user.has_perm('mailings.View_any_mailing_lists'):
            return True
        return False


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailings:mailings_list')

    def get_form_kwargs(self):
        kwargs = super(MailingCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """Метод для автоматического привязывания Пользователя к создаваемой Рассылке"""
        # Сохранение формы
        self.object = form.save()
        self.object.owner_mailing = self.request.user
        self.object.save()

        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailings:mailings_list")

    def get_form_kwargs(self):
        kwargs = super(MailingUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner_mailing:
            return MailingForm
        elif user.has_perm('mailings.Disable_mailing_lists') or user.is_staff:
            return MailingModeratorForm
        else:
            raise PermissionDenied


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер для удаления рассылки"""
    model = Mailing
    success_url = reverse_lazy("mailings:mailings_list")

    def test_func(self):
        mailing = self.get_object()
        if self.request.user == mailing.owner_mailing:
            return True
        return False


class ClientListView(LoginRequiredMixin, ListView):
    """Контроллер отображения страницы с клиентами"""
    model = Client


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Контроллер для просмотра клиента"""
    model = Client

    def test_func(self):
        client = self.get_object()
        if self.request.user == client.owner_client:
            return True
        return False


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:clients_list')

    def form_valid(self, form):
        """Метод для автоматического привязывания Пользователя к создаваемому Клиенту"""
        # Сохранение формы
        self.object = form.save()
        self.object.owner_client = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:clients_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner_client:
            return ClientForm
        else:
            raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер для удаления клиента"""
    model = Client
    success_url = reverse_lazy('mailings:clients_list')

    def test_func(self):
        client = self.get_object()
        if self.request.user == client.owner_client:
            return True
        return False


class MessageListView(LoginRequiredMixin, ListView):
    """Контроллер отображения страницы с сообщениями"""
    model = Message


class MessageDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Контроллер для просмотра сообщения"""
    model = Message

    def test_func(self):
        user = self.request.user
        message = self.get_object()
        if user == message.owner_message:
            return True
        elif user.has_perm('users.View_the_list_of_service_users'):
            return True
        return False


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:messages_list')

    def form_valid(self, form):
        """Метод для автоматического привязывания Пользователя к создаваемому Клиенту"""
        # Сохранение формы
        self.object = form.save()
        self.object.owner_message = self.request.user
        self.object.save()

        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер для редактирования сообщений"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailings:messages_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner_message:
            return MessageForm
        else:
            raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер для удаления сообщений"""
    model = Message
    success_url = reverse_lazy('mailings:messages_list')

    def test_func(self):
        message = self.get_object()
        if self.request.user == message.owner_message:
            return True
        return False


class ContactsView(TemplateView):
    template_name = 'mailings/contacts.html'

    def post(self, request):
        name = request.POST.get('name', '')
        phone = request.POST.get('phone', '')
        message = request.POST.get('message', '')
        print(f'Имя:{name}, тел.:{phone}, сообщение: {message}')
        return HttpResponseRedirect(self.request.path)


def mailing_status(request, pk):
    """
    Функция для Модератора по смене активности рассылки.
    """
    status = get_object_or_404(Mailing, pk=pk)
    if status.is_active is True:
        status.is_active = False
    elif status.is_active is False:
        status.is_active = True
    status.save()
    return redirect(reverse("mailings:mailings_list"))


class HomePage(TemplateView):
    """
    Контроллер домашней страницы
    """

    template_name = 'mailings/home.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['mailing_count'] = Mailing.objects.all().count()
        context_data["active_mailing_count"] = Mailing.objects.filter(is_active=True).count()
        context_data["unique_clients_count"] = Client.objects.all().distinct('email').count()
        blogs_list = list(Blog.objects.all())
        context_data['random_blogs'] = sample(blogs_list, min(len(blogs_list), 3))
        return context_data


class MailingAttemptView(LoginRequiredMixin, ListView):
    """Контроллер для просмотра попыток рассылки"""
    model = MailingAttempt

    form_class = MailingAttemptForm

    def get_queryset(self):
        user_id = self.request.user.id
        mailing_ids = Mailing.objects.all().filter(owner_mailing=user_id).values('id')
        queryset = MailingAttempt.objects.filter(mailing_id__in=mailing_ids)

        return queryset

    def get_context_data(self, *args, **kwargs):
        user_id = self.request.user.id
        mailing_ids = Mailing.objects.all().filter(owner_mailing=user_id).values('id')
        context_data = super().get_context_data(*args, **kwargs)
        context_data['total'] = MailingAttempt.objects.all()
        context_data['total_count'] = MailingAttempt.objects.filter(mailing_id__in=mailing_ids).count()
        context_data['success_count'] = MailingAttempt.objects.filter(mailing_id__in=mailing_ids,
                                                                      status='Отправлено').count()
        context_data['error_count'] = MailingAttempt.objects.filter(mailing_id__in=mailing_ids, status='Ошибка').count()
        return context_data

mailings/templates/mailings/blog_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="card mb-4 box-shadow">
                {% if object.preview %}
                <img src="{{ object.preview | media_filter}}">
                {% else %}
                <img src="{% static 'images/default.jpg' %}">
                {% endif %}
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">{{object.title}}</h5>
                    <h6 class="my-0 font-weight-normal">Слаг имя: {{object.slug}}</h6>
                    <h6 class="my-0 font-weight-normal">{{object.content}}</h6>
                    <h6 class="my-0 font-weight-normal">Запись создана: {{object.created_at}}</h6>
                    <h6 class="my-0 font-weight-normal">Количество просмотров: {{object.count_views}}</h6>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary" role="button"
                       href="{% url 'catalog:blog_list' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/blog_form.html
{% extends 'catalog/home.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if not object %}
                        Опубликовать
                        {% else %}
                        Сохранить
                        {% endif %}
                    </button>
                    <a class="btn btn-primary" role="button" href="{% url 'catalog:blog_list' %}">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_confirm_delete.html
{% extends 'mailings/index.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    <h5 class="my-0 font-weight-normal">Удалить клиента - {{ object.pk }}</h5>
                    <a class="btn btn-primary" role="button" href="{% url 'mailings:clients_list' %}">Отмена</a>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_detail.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">{{ client.email }}</h5>
                    <h6 class="my-0 font-weight-normal">{{ client.fio }}</h6>
                    <h6 class="my-0 font-weight-normal">{{ client.comment }}</h6>


                </div>
                <div class="card-body">
                    <a class="btn btn-primary" role="button"
                       href="{% url 'mailings:clients_list' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_form.html
{% extends 'mailings/index.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            {% if object %}
                            Редактирование клиента
                             {% else %}
                            Создание нового клиента
                            {% endif %}
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/contacts.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Контакты</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
{% include 'mailings/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>РОССИЯ</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>5936564872</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Чайковский</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Введите текст сообщения" required>
                            </textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% include 'mailings/includes/inc_footer.html' %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Главная - "ПОЧТАЛЬОН"</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

{% include 'mailings/includes/inc_menu.html' %}

{% block content %}
{% endblock %}

{% include 'mailings/includes/inc_footer.html' %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

<div class="row text-center">
    {% if not perms.mailings.View_any_mailing_lists and not perms.mailings.Disable_mailing_lists %}
    <a class="btn mb-3 btn-lg btn-block btn-outline-primary" href="{% url 'mailings:mailing_create'%}"
       role="button">Добавить рассылку</a>
    {% endif %}
    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
            {% if perms.mailings.View_any_mailing_lists and perms.mailings.Disable_mailing_lists or user == object.owner_mailing %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">Номер рассылки: {{ object.id }}</h6>
                        <h6 class="my-0 font-weight-normal">Тема рассылки: {{object.message | truncatechars:40}}</h6>
                        <h6 class="my-0 font-weight-normal">Дата и время рассылки: {{object.start_mailing }}</h6>
                        {% if object.is_active == True %}
                        <h6 class="my-0 font-weight-normal">Активна</h6>
                        {% else %}
                        <h6 class="my-0 font-weight-normal">Неактивна</h6>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <a class="btn mb-1 btn-lt btn btn-primary" role="button"
                               href="{% url 'mailings:mailing_info' object.pk %}">Подробнее</a>
                             <a class="btn mb-1 btn-lt btn btn-primary" role="button"
                               href="{% url 'mailings:mailing_update' object.pk %}">Редактировать</a>
                            {% if perms.mailings.View_any_mailing_lists and perms.mailings.Disable_mailing_lists %}
                            {% if object.is_active %}
                            <a class="btn btn-danger" role="button"
                              href="{% url 'mailings:mailing_status' object.pk %}">Отключить рассылку</a>
                              {% else %}
                            <a class="btn btn-success" role="button"
                              href="{% url 'mailings:mailing_status' object.pk %}">Включить рассылку</a>
                            {% endif %}
                            {% endif %}
                            {% if user == object.owner_mailing %}
                            <a class="btn mb-1 btn-lt btn btn-danger" role="button"
                               href="{% url 'mailings:mailing_delete' object.pk %}">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/message_list.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

<div class="row text-center">
    {% if not perms.mailings.View_any_mailing_lists %}
    <a class="btn mb-3 btn-lg btn-block btn-outline-primary" href="{% url 'mailings:message_create'%}"
       role="button">Добавить сообщение</a>
    {% endif %}
    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
            {% if perms.mailings.View_any_mailing_lists or user == object.owner_message %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">Тема: {{object.subject}}</h6>
                        <h6 class="my-0 font-weight-normal">Сообщение: {{object.message | truncatechars:40}}</h6>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <a class="btn mb-1 btn-lt btn btn-primary" role="button"
                               href="{% url 'mailings:message_info' object.pk %}">Подробнее</a>
                            {% if user == object.owner_message %}
                            <a class="btn mb-1 btn-lt btn btn-primary" role="button"
                               href="{% url 'mailings:message_update' object.pk %}">Редактировать</a>
                            <a class="btn mb-1 btn-lt btn btn-danger" role="button"
                               href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}