blogs/urls.py
from blogs.apps import BlogConfig
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    # path('', HomePage.as_view(), name='home'),
    # path('blogs/', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='blog_info'),
    path('create', BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    ContactsView, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, MailingAttemptView, \
    mailing_status, HomePage

app_name = MailingsConfig.name

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('mailings/', MailingListView.as_view(), name='mailings_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_info'),
    path('mailings/create', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('attempts/', MailingAttemptView.as_view(), name='attempts_info'),
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_info'),
    path('clients/create', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('messages/', MessageListView.as_view(), name='messages_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_info'),
    path('messages/create', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('contacts/', cache_page(60)(ContactsView.as_view()), name='contacts'),
    path("activation/<int:pk>/", mailing_status, name="mailing_status"),

]

blog/models.py
from django.db import models
from django.utils.text import slugify
from users.models import User

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    """Модель для блога"""
    title = models.CharField(max_length=120, verbose_name="заголовок", unique=True)
    slug = models.CharField(max_length=120, verbose_name="слаг", unique=True)
    content = models.TextField(verbose_name="содержимое")
    preview = models.ImageField(upload_to="blog/images", verbose_name="превью(изображение)", **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name="дата публикации")
    published = models.BooleanField(verbose_name="признак публикации", default=False)
    count_views = models.PositiveIntegerField(verbose_name="счетчик просмотров", default=0, **NULLABLE)

    class Meta:
        db_table = "blog"
        verbose_name = "блог"
        verbose_name_plural = "блоги"
        ordering = ("count_views",)

    def __str__(self):
        return f"{self.title}, {self.content}"

blogs/models.py
from django.db import models
from django.utils.text import slugify
from users.models import User

NULLABLE = {"blank": True, "null": True}
Permissions = [('View_any_entries', 'Просматривать любые записи'),
               ('Edit_entries', 'Редактировать запись'), ]


class Blog(models.Model):
    """Модель для блога"""
    title = models.CharField(max_length=120, verbose_name="заголовок", unique=True)
    slug = models.CharField(max_length=120, verbose_name="слаг", unique=True)
    content = models.TextField(verbose_name="содержимое")
    preview = models.ImageField(upload_to="blogs/images", verbose_name="превью(изображение)", **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name="дата публикации")
    published = models.BooleanField(verbose_name="признак публикации", default=False)
    count_views = models.PositiveIntegerField(verbose_name="счетчик просмотров", default=0, **NULLABLE)
    owner_blog = models.ForeignKey(User, related_name='blogs', verbose_name='Автор статьи', on_delete=models.SET_NULL,
                                   **NULLABLE)

    class Meta:
        db_table = "blog"
        verbose_name = "блог"
        verbose_name_plural = "блоги"
        ordering = ("count_views",)
        permissions = Permissions

    def __str__(self):
        return f"{self.title}, {self.content}"

blogs/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField

from blogs.models import Blog


class FormMixin:
    """Класс для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogForm(FormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ('count_views', 'slug', 'created_at', 'owner_blog',)


class BlogModeratorForm(FormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ('count_views', 'slug', 'created_at', 'owner_blog',)

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blogs.forms import BlogForm, BlogModeratorForm
from blogs.models import Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mailings:home')

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogs.Edit_entries'):
            return BlogModeratorForm
        else:
            raise PermissionDenied

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogModeratorForm

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogs.Edit_entries'):
            return BlogModeratorForm
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse('blogs:blog_info', args=[self.kwargs.get('slug')])


class BlogDeleteView(DeleteView):
    model = Blog

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('blogs.Edit_entries'):
            return BlogModeratorForm
        else:
            raise PermissionDenied

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'mailings/index.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    <h5 class="my-0 font-weight-normal">Удалить запись - {{ object.title }}</h5>
                    <a class="btn btn-primary" role="button" href="{% url 'mailings:home' %}">Отмена</a>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="card mb-4 box-shadow">
                {% if object.preview %}
                <img src="{{ object.preview | media_filter}}">
                {% else %}
                <img src="{% static 'images/default.jpg' %}">
                {% endif %}
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">{{object.title}}</h5>
                    <h6 class="my-0 font-weight-normal">{{object.content}}</h6>
                    <h6 class="my-0 font-weight-normal">Запись создана: {{object.created_at}}</h6>
                    <h6 class="my-0 font-weight-normal">Количество просмотров: {{object.count_views}}</h6>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary" role="button" href="{% url 'mailings:home' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'mailings/index.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if not object %}
                        Опубликовать
                        {% else %}
                        Сохранить
                        {% endif %}
                    </button>
                    <a class="btn btn-primary" role="button" href="{% url 'mailings:home' %}">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}
<div class="row text-center">
    <a class="btn mb-3 btn-lg btn-block btn-outline-primary" href="{% url 'blogs:blog_create'%}"
       role="button">Добавить запись</a>
    {% for object in object_list %}
    <div class="col-4 col-xs-12">
        <div class="card mb-3 box-shadow">
            {% if object.preview %}
            <img src="{{ object.preview | media_filter }}" class="img-fluid">
            {% else %}
            <img src="{% static 'images/default.jpg' %}">
            {% endif %}
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">{{ object.title }}</h5>
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.content |truncatechars:50}}</p>
                <h4 class="card-text"> {{ object.count_views }} просмотров </h4>
                <a class="btn btn-primary" role="button"
                   href="{% url 'blogs:blog_info' object.slug %}">Подробнее</a>
                <a class="btn btn-primary" role="button"
                   href="{% url 'blogs:blog_update' object.slug %}">Редактировать</a>
                <a class="btn btn-danger" role="button"
                   href="{% url 'blogs:blog_delete' object.slug %}">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}