blogs/urls.py
from blogs.apps import BlogConfig
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    # path('', HomePage.as_view(), name='home'),
    # path('blogs/', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='blog_info'),
    path('create', BlogCreateView.as_view(), name='blog_create'),
    path('<slug:slug>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<slug:slug>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),

]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, send_message, user_status
from users.views import UserListView
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = UsersConfig.name

urlpatterns = [
    path('', UserListView.as_view(), name='users_list'),
    path("activation/<int:pk>/", user_status, name="user_status"),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='mailings/index.html'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('message/', send_message, name='send_message'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done'),
        ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm',
    ),
    path(
        'password-reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {"blank": True, "null": True}
Permissions = [('View_the_list_of_service_users', 'Просматривать список пользователей сервиса'),
               ('Block_users_of_the_service', 'Блокировать пользователей сервиса'), ]


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    phone = models.CharField(max_length=30, verbose_name='Контактный телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Автар', **NULLABLE)
    country = models.CharField(max_length=40, verbose_name='Страна', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='Токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        ordering = ("email",)
        permissions = Permissions

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mailings.forms import FormMixin
from users.models import User


class UserRegisterForm(FormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(FormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.views.generic import CreateView, UpdateView, ListView
from users.models import User
from users.forms import UserRegisterForm, UserProfileForm
from django.urls import reverse_lazy, reverse
import secrets
from django.core.mail import send_mail
from config.settings import EMAIL_HOST_USER
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """Контроллер отображения страницы с сообщениями"""
    model = User

    def test_func(self):
        user = self.request.user
        if user.has_perm('users.Block_users_of_the_service'):
            return True
        return False


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты для завершения регистрации',
            message=f'Для подтверждения почты необходимо перейти по ссылке: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('mailings:mailings_list')

    def get_object(self, queryset=None):
        return self.request.user


def send_message(request):
    return render(request, "users/send_message.html")


def user_status(request, pk):
    """
    Функция для Модератора по смене активности пользователя.
    """
    status = get_object_or_404(User, pk=pk)
    if status.is_active is True:
        status.is_active = False
    elif status.is_active is False:
        status.is_active = True
    status.save()
    return redirect(reverse("users:users_list"))

users/templates/users/login.html
{% extends 'mailings/index.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Вход
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти</button>
                    </div>
                    <a class="btn mb-1 btn-lt btn btn-primary" role="button"
                       href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailings/index.html' %}
{% block content %}
<p>Пароль для пользователя успешно сменен</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailings/index.html' %}
{% block content %}
  {% if validlink %}
    <h1>Смена пароля</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Подтвердить</button>
    </form>
  {% else %}
    <p>
      Вероятно ссылка неверна или уже была использована
    </p>
  {% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailings/index.html' %}
{% load i18n %}
{% block content %}
Инструкция по восстановлению пароля отправлена на указанный email
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktranslate %}
Письмо для сброса пароля от {{ site_name }}.
{% endblocktranslate %}
{% translate 'Имя пользователя:' %} {{ user.get_username }}
{% translate "Для установки нового пароля перейдите по ссылке:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'mailings/index.html' %}
{% block content %}
  <h3>Восстановление пароля</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/index.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Регистрация
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/index.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            Профиль
                        </h4>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

<div class="row text-center">

        <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
            {% if not object.is_superuser and not object.is_staff %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    {% if object.avatar %}
                    <img src="{{ object.avatar | media_filter }}">
                    {% else %}
                    <img src="{% static 'images/default.jpg' %}">
                    {% endif %}
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">Имя: {{object.first_name}}</h6>
                        <h6 class="my-0 font-weight-normal">Фамилия: {{object.last_name}}</h6>
                        <h6 class="my-0 font-weight-normal">Электронная почта: {{object.email }}</h6>
                        {% if object.is_active %}
                        <h6 class="my-0 font-weight-normal">Статус: Активный пользователь</h6>
                        {% else %}
                        <h6 class="my-0 font-weight-normal">Статус: Заблокирован</h6>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            {% if object.is_active %}
                            <a class="btn btn-danger" role="button"
                              href="{% url 'users:user_status' object.pk %}">Заблокировать пользователя</a>
                              {% else %}
                            <a class="btn btn-success" role="button"
                              href="{% url 'users:user_status' object.pk %}">Разблокировать пользователя</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% endfor %}
            </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_list_.html
{% extends 'mailings/index.html' %}
{% load my_tags %}
{% load static %}
{% block content %}

<div class="row text-center">
    {% if not perms.users.View_the_list_of_service_users and not perms.users.Block_users_of_the_service %}
        <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">Имя: {{object.first_name}}</h6>
                        <h6 class="my-0 font-weight-normal">Фамилия: {{object.last_name}}</h6>
                        <h6 class="my-0 font-weight-normal">Электронная почта: {{object.email }}</h6>
                        {% if object.is_active %}
                        <h6 class="my-0 font-weight-normal">Статус: Активный пользователь</h6>
                        {% else %}
                        <h6 class="my-0 font-weight-normal">Статус: Заблокирован</h6>
                        {% endif %}

                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            {% if object.is_active %}
                            <a class="btn btn-danger" role="button"
                              href="{% url 'users:user_status' object.pk %}">Заблокировать пользователя</a>
                              {% else %}
                            <a class="btn btn-success" role="button"
                              href="{% url 'users:user_status' object.pk %}">Разблокировать пользователя</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
    </div>
    {% endif %}




</div>
{% endblock %}